[package]
name = "test"
version = "0.1.0"
authors = ["SpongeData <info@spongedata.cz> (https://spongedata.cz/)"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solrdrv = { path = "./solrdrv" }
